### ISSUE TITLE
Certificate chain verification in circom

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/openpassport#37]
The electronic passports trust chain has two levels: 
- top-level certificates (CSCAs) are used to sign intermediate certificates (DSCs) 
- intermediate certificates (DSCs) are used to sign passports

Right now, we get the [list of DSCs from the ICAO website](https://github.com/zk-passport/proof-of-passport/blob/main/registry) and check if passports are signed by [any of them](https://github.com/zk-passport/proof-of-passport/blob/main/registry/outputs/signature_algorithms.json). However, we strongly suspect this list is incomplete as countries have no obligation to transmit these intermediate certificates, and the top ones are supposed to be the authoritative source.

We should work on verifying the whole certificate chain, which follows the X.509 format. The MynaWallet team has a circuit in which they are [parsing one with fixed indexes](https://github.com/MynaWallet/monorepo/blob/nico/selective-disclosure/packages/circom-circuit/src/selective-disclosure.circom), but we should build a more modular chain certificate verifier that supports multiple signature algorithms and parsing any data from certificates. This would also be super useful to projects like zk AppAttest and zk DNS trust chain verification that also require X.509 chain verification.

[Some work has been done](https://github.com/zkCert/halo2-zkcert) by Richard and Sachin in halo2.

The endgame for us would be having only the root of a merkle tree containing the [CSCAs from the masterlist](https://download.pkd.icao.int) on chain, then verifying the whole chain in the circuit.

**Comment by mdabir1203** [comment]
From what I understood I have two questions : 

- by root of merkle tree means its the **hash** of all the documents from csca , right ?
- Can you tell me what is the structure of the merkle tree for CSCA master list ?

**Comment by remicolin** [comment]
update on the issue:
sha256 rsa ✅ -> [code](https://github.com/zk-passport/proof-of-passport/blob/dev/circuits/circuits/dsc/dsc_sha256_rsa.circom)
sha1 rsa ✅ -> [code](https://github.com/zk-passport/proof-of-passport/blob/dev/circuits/circuits/dsc/dsc_sha1_rsa.circom)
sha256 rsapss 🚧 -> [issue](https://github.com/zk-passport/proof-of-passport/pull/141)

TODO (help wanted)
sha384 ecdsa (secpr1)

**Comment by zarah-s** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
With my strong background in Rust, Solidity and JavaScript, I can apply my expertise in solving this issue

**Comment by HumbertoTM10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I have 4 years working in development environments, have encountered several challenges, requests and teams focusing in reusable and efficient code, so that gives me a better understanding of the code and how to solve problems efficiently.

### How I plan on tackling this issue
I would focus in a comprehensive solution involving several key components: a certificate parsing module to extract relevant fields, a signature verification module supporting multiple cryptographic algorithms, and a chain building and verification module to validate the entire chain from end-entity certificates to root CSCAs. Additionally, we plan to integrate a Merkle tree for storing CSCAs on-chain, facilitating secure and efficient verification. The approach also includes leveraging existing work in halo2 for circuit implementation, ensuring scalability and performance. By prioritizing security, including certificate revocation checks and algorithm agility, this solution will also support related projects like zk AppAttest and zk DNS, providing a robust and future-proof certificate verification system.
